_merge: !include _base.yaml
bars:
  primary-bar: !include _primary_bar.yaml
widgets:
  home: !include widgets/home.yaml
  apps: !include widgets/apps.yaml
  disk: !include widgets/disk.yaml
  cava: !include widgets/cava.yaml
  media: !include widgets/media.yaml
  clock: !include widgets/clock.yaml
  volume: !include widgets/volume.yaml
  weather: !include widgets/weather.yaml
  systray: !include widgets/systray.yaml
  taskbar: !include widgets/taskbar.yaml
  battery: !include widgets/battery.yaml
  pomodoro: !include widgets/pomodoro.yaml
  launchpad: !include widgets/launchpad.yaml
  microphone: !include widgets/microphone.yaml
  power_menu: !include widgets/power_menu.yaml
  active_window: !include widgets/active_window.yaml
  notifications: !include widgets/notifications.yaml
  komorebi_workspaces: !include widgets/komorebi_workspaces.yaml
  komorebi_active_layout: !include widgets/komorebi_active_layout.yaml
